<a href="https://colab.research.google.com/github/mmaia2022/UFRN_BIB/blob/main/ufrn_bib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Unificando em um dataframe usando pandas, os arquivos de nome emprestimos em formato csv e Apache paquet
# código gerado pelo Gemini  o colab para agilizar o código, que analisei para veificar e entender
# inclui a variável filepath para informar o caminho dos arquivos

import pandas as pd
import glob

# Lista para armazenar os DataFrames de cada arquivo
dfs = []
filepath = '/content/sample_data/ufrn_bib/'
# Loop para ler os arquivos CSV de cada ano
for year in range(2010, 2021):
  for i in range(1, 3):  # Assumindo que você tem dois arquivos para cada ano (emprestimos-2010-1.csv, emprestimos-2010-2.csv, etc.)
    filename = filepath + f'emprestimos-{year}{i}.csv'  # Nome do arquivo
    try:
      # Ler o arquivo CSV e adicionar ao DataFrame
      df = pd.read_csv(filename)
      dfs.append(df)
    except FileNotFoundError:
      print(f"Arquivo {filename} não encontrado.")

# Concatenar todos os DataFrames em um único DataFrame
df_final = pd.concat(dfs, ignore_index=True)

# Imprimir o DataFrame final
print(df_final)

Arquivo /content/sample_data/ufrn_bib/emprestimos-20202.csv não encontrado.
         id_emprestimo codigo_barras                 data_renovacao  \
0               709684       L095049                            NaN
1               709685       L167050                            NaN
2               709686    2006017618  2010/01/26 08:07:01.738000000
3               709687       L184117  2010/01/18 11:07:46.470000000
4               709684       L095049                            NaN
...                ...           ...                            ...
2258013        2989086    2008047044                            NaN
2258014        2989087    2008047047                            NaN
2258015        2989088    2010052905                            NaN
2258016        2989089    2010048023                            NaN
2258017        2989090    2013106838                            NaN

                       data_emprestimo                 data_devolucao  \
0        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1        2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2        2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3        2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
4        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
...                                ...                            ...
2258013  2020/05/05 19:51:06.059000000  2021/05/13 14:53:31.000000000
2258014  2020/05/05 19:51:06.135000000  2021/05/13 14:53:38.000000000
2258015  2020/05/05 19:51:06.164000000  2021/05/13 15:01:46.000000000
2258016  2020/06/09 11:54:02.669000000  2021/07/21 15:33:55.000000000
2258017  2020/06/09 11:54:02.852000000  2021/07/21 15:33:45.000000000

         matricula_ou_siape             tipo_vinculo_usuario
0              2.008023e+09               ALUNO DE GRADUAÇÃO
1              2.008023e+09               ALUNO DE GRADUAÇÃO
2              2.008112e+09           ALUNO DE PÓS-GRADUAÇÃO
3              2.007211e+08               ALUNO DE GRADUAÇÃO
4              2.008023e+09               ALUNO DE GRADUAÇÃO
...                     ...                              ...
2258013        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO
2258017        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO

[2258018 rows x 7 columns]

In [11]:
df_final

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

In [ ]:
# analisando tipos de dados nas columas
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2162179 entries, 0 to 2162178
Data columns (total 7 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
dtypes: float64(1), int64(1), object(5)
memory usage: 115.5+ MB

In [23]:
# Encontrando e removendo linhas duplicadas no df_concat
duplicate_rows = df_final[df_final.duplicated(keep=False)]  # Encontra todas as linhas duplicadas
print("Linhas duplicadas encontradas:")
print(duplicate_rows)

df_concat = df_final.drop_duplicates()  # Remove as linhas duplicadas, mantendo apenas a primeira ocorrência

# Verificando se ainda existem duplicatas
# print("\nNúmero de linhas duplicadas após a limpeza:", df_final_cleaned().sum())

# Opcional: salvar o DataFrame limpo em um novo arquivo
# df_concat_cleaned.to_csv("df_concat_cleaned.csv", index=False)

print("\nDataFrame após a limpeza:")
print(df_concat)

Linhas duplicadas encontradas:
         id_emprestimo codigo_barras                 data_renovacao  \
0               709684       L095049                            NaN
1               709685       L167050                            NaN
2               709686    2006017618  2010/01/26 08:07:01.738000000
3               709687       L184117  2010/01/18 11:07:46.470000000
4               709684       L095049                            NaN
...                ...           ...                            ...
1504570        2461095    2014007744                            NaN
1504571        2461096    2016005538                            NaN
1504572        2461097    2014083427                            NaN
1504573        2461098    2014049460                            NaN
1504574        2461099    2012008348  2016/06/27 20:35:46.855000000

                       data_emprestimo                 data_devolucao  \
0        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1        2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2        2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3        2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
4        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
...                                ...                            ...
1504570  2016/06/14 11:16:34.459000000  2016/06/22 08:04:39.000000000
1504571  2016/06/14 11:16:58.596000000  2016/07/04 16:07:41.000000000
1504572  2016/06/14 11:17:29.152000000  2016/06/16 09:17:19.000000000
1504573  2016/06/14 11:18:59.254000000  2016/06/26 13:44:13.000000000
1504574  2016/06/14 11:20:33.254000000  2016/07/11 14:37:29.000000000

         matricula_ou_siape    tipo_vinculo_usuario
0              2.008023e+09      ALUNO DE GRADUAÇÃO
1              2.008023e+09      ALUNO DE GRADUAÇÃO
2              2.008112e+09  ALUNO DE PÓS-GRADUAÇÃO
3              2.007211e+08      ALUNO DE GRADUAÇÃO
4              2.008023e+09      ALUNO DE GRADUAÇÃO
...                     ...                     ...
1504570        2.016013e+10      ALUNO DE GRADUAÇÃO
1504571        2.016014e+10      ALUNO DE GRADUAÇÃO
1504572        2.016014e+10      ALUNO DE GRADUAÇÃO
1504573        2.017005e+10      ALUNO DE GRADUAÇÃO
1504574        2.015022e+09      ALUNO DE GRADUAÇÃO

[63 rows x 7 columns]

DataFrame após a limpeza:
         id_emprestimo codigo_barras                 data_renovacao  \
0               709684       L095049                            NaN
1               709685       L167050                            NaN
2               709686    2006017618  2010/01/26 08:07:01.738000000
3               709687       L184117  2010/01/18 11:07:46.470000000
8               709688    2007027500  2010/01/19 15:59:26.464000000
...                ...           ...                            ...
2258013        2989086    2008047044                            NaN
2258014        2989087    2008047047                            NaN
2258015        2989088    2010052905                            NaN
2258016        2989089    2010048023                            NaN
2258017        2989090    2013106838                            NaN

                       data_emprestimo                 data_devolucao  \
0        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1        2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2        2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3        2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
8        2010/01/04 08:27:33.569000000  2010/02/03 13:06:30.662000000
...                                ...                            ...
2258013  2020/05/05 19:51:06.059000000  2021/05/13 14:53:31.000000000
2258014  2020/05/05 19:51:06.135000000  2021/05/13 14:53:38.000000000
2258015  2020/05/05 19:51:06.164000000  2021/05/13 15:01:46.000000000
2258016  2020/06/09 11:54:02.669000000  2021/07/21 15:33:55.000000000
2258017  2020/06/09 11:54:02.852000000  2021/07/21 15:33:45.000000000

         matricula_ou_siape             tipo_vinculo_usuario
0              2.008023e+09               ALUNO DE GRADUAÇÃO
1              2.008023e+09               ALUNO DE GRADUAÇÃO
2              2.008112e+09           ALUNO DE PÓS-GRADUAÇÃO
3              2.007211e+08               ALUNO DE GRADUAÇÃO
8              2.009046e+09               ALUNO DE GRADUAÇÃO
...                     ...                              ...
2258013        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO
2258017        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO

[2257981 rows x 7 columns]

In [25]:
# Concatenar o  DataFrame df_final com o arquivo dados_exemplares.parquet em um único Data Frame de nome df_concat, sendo que a coluna codigo_barras é a chave em comum

# Importando em um dataframe df_exemplares 'dados_exemplares.parquet'
df_exemplares = pd.read_parquet(filepath + 'dados_exemplares.parquet')

# Fazendo o Merge dos dois dataframes df_final e df_exemplares em um único dataframe df_concat com a coluna chave sendo codigo_barras
#df_concat = pd.merge(df_final, df_exemplares, on='codigo_barras', how='inner')
df_concat = df_concat.merge(df_exemplares)

# Print do DataFrame
print(df_concat)

         id_emprestimo codigo_barras                 data_renovacao  \
0               709684       L095049                            NaN
1               709685       L167050                            NaN
2               709686    2006017618  2010/01/26 08:07:01.738000000
3               709687       L184117  2010/01/18 11:07:46.470000000
4               709684       L095049                            NaN
...                ...           ...                            ...
2072553        2989086    2008047044                            NaN
2072554        2989087    2008047047                            NaN
2072555        2989088    2010052905                            NaN
2072556        2989089    2010048023                            NaN
2072557        2989090    2013106838                            NaN

                       data_emprestimo                 data_devolucao  \
0        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1        2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2        2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3        2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
4        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
...                                ...                            ...
2072553  2020/05/05 19:51:06.059000000  2021/05/13 14:53:31.000000000
2072554  2020/05/05 19:51:06.135000000  2021/05/13 14:53:38.000000000
2072555  2020/05/05 19:51:06.164000000  2021/05/13 15:01:46.000000000
2072556  2020/06/09 11:54:02.669000000  2021/07/21 15:33:55.000000000
2072557  2020/06/09 11:54:02.852000000  2021/07/21 15:33:45.000000000

         matricula_ou_siape             tipo_vinculo_usuario  id_exemplar  \
0              2.008023e+09               ALUNO DE GRADUAÇÃO        13259
1              2.008023e+09               ALUNO DE GRADUAÇÃO        70865
2              2.008112e+09           ALUNO DE PÓS-GRADUAÇÃO       195347
3              2.007211e+08               ALUNO DE GRADUAÇÃO       131639
4              2.008023e+09               ALUNO DE GRADUAÇÃO        13259
...                     ...                              ...          ...
2072553        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO       256297
2072554        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO       256406
2072555        3.067431e+06  SERVIDOR TÉCNICO-ADMINISTRATIVO       807821
2072556        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO       804885
2072557        2.020101e+10           ALUNO DE PÓS-GRADUAÇÃO      1099777

                   colecao                                         biblioteca  \
0        Acervo Circulante                     Biblioteca Central Zila Mamede
1        Acervo Circulante                     Biblioteca Central Zila Mamede
2        Acervo Circulante  Biblioteca Setorial Prof. Rodolfo Helinski - E...
3        Acervo Circulante                     Biblioteca Central Zila Mamede
4        Acervo Circulante                     Biblioteca Central Zila Mamede
...                    ...                                                ...
2072553  Acervo Circulante  Biblioteca Setorial da Faculdade de Ciências d...
2072554  Acervo Circulante  Biblioteca Setorial da Faculdade de Ciências d...
2072555  Acervo Circulante  Biblioteca Setorial da Faculdade de Ciências d...
2072556  Acervo Circulante                     Biblioteca Central Zila Mamede
2072557  Acervo Circulante                     Biblioteca Central Zila Mamede

        status_material  localizacao  registro_sistema
0               REGULAR          630              4225
1               REGULAR          647             25009
2               REGULAR          640             75019
3               REGULAR          609             44494
4               REGULAR          630              4225
...                 ...          ...               ...
2072553         REGULAR          684            110098
2072554         REGULAR          628            110171
2072555         REGULAR          653            134173
2072556         REGULAR          675             67712
2072557         REGULAR           14            205153

[2072558 rows x 13 columns]

In [26]:
# Visualizando que o merge dos dados foram funcionou.
df_concat

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072553,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098
2072554,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171
2072555,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173
2072556,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712
2072557,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153

In [17]:
# Encontrando e removendo linhas duplicadas no df_concat
duplicate_rows = df_concat[df_concat.duplicated(keep=False)]  # Encontra todas as linhas duplicadas
print("Linhas duplicadas encontradas:")
print(duplicate_rows)

Linhas duplicadas encontradas:
         id_emprestimo codigo_barras                 data_renovacao  \
0               709684       L095049                            NaN
1               709685       L167050                            NaN
2               709686    2006017618  2010/01/26 08:07:01.738000000
3               709687       L184117  2010/01/18 11:07:46.470000000
4               709684       L095049                            NaN
...                ...           ...                            ...
1351146        2461095    2014007744                            NaN
1351147        2461096    2016005538                            NaN
1351148        2461097    2014083427                            NaN
1351149        2461098    2014049460                            NaN
1351150        2461099    2012008348  2016/06/27 20:35:46.855000000

                       data_emprestimo                 data_devolucao  \
0        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
1        2010/01/04 07:44:10.750000000  2010/01/12 07:34:13.934000000
2        2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000
3        2010/01/04 08:24:21.284000000  2010/02/03 08:58:45.692000000
4        2010/01/04 07:44:10.721000000  2010/01/05 16:26:12.662000000
...                                ...                            ...
1351146  2016/06/14 11:16:34.459000000  2016/06/22 08:04:39.000000000
1351147  2016/06/14 11:16:58.596000000  2016/07/04 16:07:41.000000000
1351148  2016/06/14 11:17:29.152000000  2016/06/16 09:17:19.000000000
1351149  2016/06/14 11:18:59.254000000  2016/06/26 13:44:13.000000000
1351150  2016/06/14 11:20:33.254000000  2016/07/11 14:37:29.000000000

         matricula_ou_siape    tipo_vinculo_usuario  id_exemplar  \
0              2.008023e+09      ALUNO DE GRADUAÇÃO        13259
1              2.008023e+09      ALUNO DE GRADUAÇÃO        70865
2              2.008112e+09  ALUNO DE PÓS-GRADUAÇÃO       195347
3              2.007211e+08      ALUNO DE GRADUAÇÃO       131639
4              2.008023e+09      ALUNO DE GRADUAÇÃO        13259
...                     ...                     ...          ...
1351146        2.016013e+10      ALUNO DE GRADUAÇÃO      1106481
1351147        2.016014e+10      ALUNO DE GRADUAÇÃO      1229935
1351148        2.016014e+10      ALUNO DE GRADUAÇÃO      1172546
1351149        2.017005e+10      ALUNO DE GRADUAÇÃO      1157755
1351150        2.015022e+09      ALUNO DE GRADUAÇÃO       979548

                   colecao                                         biblioteca  \
0        Acervo Circulante                     Biblioteca Central Zila Mamede
1        Acervo Circulante                     Biblioteca Central Zila Mamede
2        Acervo Circulante  Biblioteca Setorial Prof. Rodolfo Helinski - E...
3        Acervo Circulante                     Biblioteca Central Zila Mamede
4        Acervo Circulante                     Biblioteca Central Zila Mamede
...                    ...                                                ...
1351146  Acervo Circulante  Biblioteca Setorial Prof. Alberto Moreira Camp...
1351147  Acervo Circulante                     Biblioteca Central Zila Mamede
1351148  Acervo Circulante  Biblioteca Setorial Prof. Alberto Moreira Camp...
1351149  Acervo Circulante                     Biblioteca Central Zila Mamede
1351150  Acervo Circulante                     Biblioteca Central Zila Mamede

        status_material  localizacao  registro_sistema
0               REGULAR          630              4225
1               REGULAR          647             25009
2               REGULAR          640             75019
3               REGULAR          609             44494
4               REGULAR          630              4225
...                 ...          ...               ...
1351146         REGULAR          319            180725
1351147         REGULAR          148            220879
1351148         REGULAR          328            175595
1351149         REGULAR          392            200031
1351150         REGULAR          612            112965

[61 rows x 13 columns]

In [19]:
duplicate_rows

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351146,2461095,2014007744,NaN,2016/06/14 11:16:34.459000000,2016/06/22 08:04:39.000000000,2.016013e+10,ALUNO DE GRADUAÇÃO,1106481,Acervo Circulante,Biblioteca Setorial Prof. Alberto Moreira Camp...,REGULAR,319,180725
1351147,2461096,2016005538,NaN,2016/06/14 11:16:58.596000000,2016/07/04 16:07:41.000000000,2.016014e+10,ALUNO DE GRADUAÇÃO,1229935,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,148,220879
1351148,2461097,2014083427,NaN,2016/06/14 11:17:29.152000000,2016/06/16 09:17:19.000000000,2.016014e+10,ALUNO DE GRADUAÇÃO,1172546,Acervo Circulante,Biblioteca Setorial Prof. Alberto Moreira Camp...,REGULAR,328,175595
1351149,2461098,2014049460,NaN,2016/06/14 11:18:59.254000000,2016/06/26 13:44:13.000000000,2.017005e+10,ALUNO DE GRADUAÇÃO,1157755,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,392,200031
1351150,2461099,2012008348,2016/06/27 20:35:46.855000000,2016/06/14 11:20:33.254000000,2016/07/11 14:37:29.000000000,2.015022e+09,ALUNO DE GRADUAÇÃO,979548,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,612,112965

In [30]:
# Conparando a quantidades de registros após a limpeza
df_concat_linhas = len(df_final)
df_concat_cleaned_linhas = len(df_concat)
df_dif = df_concat_linhas - df_concat_cleaned_linhas

print(f"Número de registros em df_concat........: {df_concat_linhas}")
print(f"Número de registros em df_concat_cleaned: {df_concat_cleaned_linhas}")
print(f"Número de registros excluidos...........: {df_dif}")
df_concat_cleaned

Número de registros em df_concat........: 2258018
Número de registros em df_concat_cleaned: 2072558
Número de registros excluidos...........: 185460

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
2258013,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258014,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258015,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
2258016,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
2258017,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

In [31]:
# Opcional: salvar o DataFrame limpo em um novo arquivo
df_concat.to_csv("df_concat_cleaned.csv", index=False)

In [33]:
df_concat

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647,25009
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640,75019
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609,44494
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630,4225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072553,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256297,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,684,110098
2072554,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,256406,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,628,110171
2072555,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO,807821,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,653,134173
2072556,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,804885,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,675,67712
2072557,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO,1099777,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,14,205153